appraise "rails-7" do
  gem "rails", "~> 7.0.8"
end

appraise "rails-7.1" do
  gem "rails", "~> 7.1.5"
  gem "puma", "~> 6.0"
end

appraise "rails-7.2" do
  gem "rails", "~> 7.2.2"
  gem "puma", "~> 6.0"
end

appraise "rails-8" do
  gem "rails", "~> 8.0.0"
  gem "puma", "~> 6.0"
end

appraise "rails-8.1" do
  gem "rails", "~> 8.1.0"
  gem "puma", "~> 6.0"
end
