source "https://rubygems.org"

ruby "~> 3.2"

gem "rails", "~> 7.0.4"
gem "puma", "~> 5.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "flipper"
gem "flipper-notifications", path: "../../.."

# ponytail: Rails < 8.1 patches Minitest::Runnable.run, which minitest 6
# renamed to .run_suite. Drop this pin when the oldest appraisal is Rails 8.1.
gem "minitest", "< 6"

group :development, :test do
  gem "appraisal"
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "dotenv-rails"
end

group :development do
  gem "web-console"
end
