source "https://rubygems.org"

ruby "~> 3.1"

gem "rails", "~> 7.0.4"
gem "puma", "~> 5.0"

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

gem "flipper"
gem "flipper-notifications", path: "../../.."

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem "dotenv-rails"
end

group :development do
  gem "web-console"
end
