name: Tests (Ruby)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "0 6 * * *" # 6 A.M.

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version:
          - '3.1'
          - '3.2'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Ruby version
        run: ruby -v
      - name: Run tests
        run: bundle exec rspec

  test_ruby_3_0:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - name: Ruby version
        run: ruby -v
      - name: Install dependencies
        run: gem install bundler -v 2.3.11 && bundle _2.3.11_ install
      - name: Run tests
        run: bundle exec rspec
